### ISSUE TITLE
"init_vector_store_table" function fails if optional parameter "metadata_columns" is not passed

### ISSUE THREAD

**Issue by vmanghnani** [googleapis/langchain-google-spanner-python#98]
SpannerVectorStore.init_vector_store_table(

#### Environment details

  - OS type and version:  colab:  https://colab.sandbox.google.com/github/googleapis/langchain-google-spanner-python/blob/main/docs/vector_store.ipynb
  
  
#### Steps to reproduce

  1.     Run : colab:  https://colab.sandbox.google.com/github/googleapis/langchain-google-spanner-python/blob/main/docs/vector_store.ipynb 
  
  3.  In   "SpannerVectorStore.init_vector_store_table" code cell, commentout "metadata_columns" parameter.. 
      cell's execution fails with below error:  "...TypeError: 'NoneType' object is not iterable.."

    Desired behavior: "metadata_columns" should be optional.. 

#### Code example
```python
# example
------------------------------------------------------------------------------------------------------------------------------

from langchain_google_spanner import SecondaryIndex, SpannerVectorStore, TableColumn

SpannerVectorStore.init_vector_store_table(
    instance_id=INSTANCE,
    database_id=DATABASE,
    table_name=TABLE_NAME,
    # Customize the table creation
    id_column="row_id",
    #metadata_columns=[
    #    TableColumn(name="metadata", type="JSON", is_null=True),
    #    TableColumn(name="title", type="STRING(MAX)", is_null=False),
    #],
    secondary_indexes=[
        SecondaryIndex(index_name="row_id_and_title", columns=["row_id", "title"])
    ],
)------------------------------------------------------------------------------------------------------------------------------

**Comment by gauravpurohit06** [comment]
Thank you for raising the issue @vmanghnani. I have raised the PR to fix it.
